# Generated by Django 3.2.3 on 2021-06-16 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDserial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_address',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CRUDserial.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
